/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ufnwklopgntlbrostwtz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbndrbG9wZ250bGJyb3N0d3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNTczMzYsImV4cCI6MjA3OTYzMzMzNn0.GXLGa_o22KNRarTEgp-yaHStl6yv0R0l5eJcpm-3-VQ"